# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb_api1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='cover',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
