# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sb_api1', '0004_auto_20161104_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sb_api1.contents'),
        ),
    ]
